% Sorting into groups
clc; clear all; close all;
cd 'C:\Users\akgra\OneDrive\Documents\UCL REAT\Group Research Project\Testing'
%%
USE = readtable("Ease of Use.xlsx");

EaseofUseSM_matrix = table2array(USE(1:14,3:13));

EaseofUseSM_orderofquestionC = reshape(EaseofUseSM_matrix,[1,154]);

EaseofUseSM_subjectorderC = [EaseofUseSM_matrix(1,1:11), EaseofUseSM_matrix(2,1:11),... 
                EaseofUseSM_matrix(3,1:11), EaseofUseSM_matrix(4,1:11),...
                EaseofUseSM_matrix(5,1:11), EaseofUseSM_matrix(6,1:11),...
                EaseofUseSM_matrix(7,1:11), EaseofUseSM_matrix(8,1:11),...
                EaseofUseSM_matrix(9,1:11), EaseofUseSM_matrix(10,1:11),...
                EaseofUseSM_matrix(11,1:11), EaseofUseSM_matrix(12,1:11),...
                EaseofUseSM_matrix(13,1:11), EaseofUseSM_matrix(14,1:11)];
            

EaseofUseMMC_matrix = table2array(USE(18:31,3:13));

EaseofUseMMC_orderofquestionC = reshape(EaseofUseMMC_matrix,[1,154]);

EaseofUseMMC_subjectorderC = [EaseofUseMMC_matrix(1,1:11), EaseofUseMMC_matrix(2,1:11),... 
                EaseofUseMMC_matrix(3,1:11), EaseofUseMMC_matrix(4,1:11),...
                EaseofUseMMC_matrix(5,1:11), EaseofUseMMC_matrix(6,1:11),...
                EaseofUseMMC_matrix(7,1:11), EaseofUseMMC_matrix(8,1:11),...
                EaseofUseMMC_matrix(9,1:11), EaseofUseMMC_matrix(10,1:11),...
                EaseofUseMMC_matrix(11,1:11), EaseofUseMMC_matrix(12,1:11),...
                EaseofUseMMC_matrix(13,1:11), EaseofUseMMC_matrix(14,1:11)];

            
EaseofUseORT_matrix = table2array(USE(35:48,3:13));

EaseofUseORT_orderofquestionC = reshape(EaseofUseORT_matrix,[1,154]);

EaseofUseORT_subjectorderC = [EaseofUseORT_matrix(1,1:11), EaseofUseORT_matrix(2,1:11),... 
                EaseofUseORT_matrix(3,1:11), EaseofUseORT_matrix(4,1:11),...
                EaseofUseORT_matrix(5,1:11), EaseofUseORT_matrix(6,1:11),...
                EaseofUseORT_matrix(7,1:11), EaseofUseORT_matrix(8,1:11),...
                EaseofUseORT_matrix(9,1:11), EaseofUseORT_matrix(10,1:11),...
                EaseofUseORT_matrix(11,1:11), EaseofUseORT_matrix(12,1:11),...
                EaseofUseORT_matrix(13,1:11), EaseofUseORT_matrix(14,1:11)];
            
            
EaseofUseSM_subjectorderA = table2array(USE(50,3:13));
EaseofUseMMC_subjectorderA = table2array(USE(52,3:13));
EaseofUseORT_subjectorderA = table2array(USE(54,3:13));

EaseofUseSM_subjectorderB = table2array(USE(56,3:13));
EaseofUseMMC_subjectorderB = table2array(USE(58,3:13));
EaseofUseORT_subjectorderB = table2array(USE(60,3:13));


%%

Learn = readtable("Ease of Learning.xlsx");

EaseofLearnSM_matrix = table2array(Learn(1:14,3:6));

EaseofLearnSM_orderofquestionC = reshape(EaseofLearnSM_matrix,[1,56]);

EaseofLearnSM_subjectorderC = [EaseofLearnSM_matrix(1,1:4), EaseofLearnSM_matrix(2,1:4),... 
                EaseofLearnSM_matrix(3,1:4), EaseofLearnSM_matrix(4,1:4),...
                EaseofLearnSM_matrix(5,1:4), EaseofLearnSM_matrix(6,1:4),...
                EaseofLearnSM_matrix(7,1:4), EaseofLearnSM_matrix(8,1:4),...
                EaseofLearnSM_matrix(9,1:4), EaseofLearnSM_matrix(10,1:4),...
                EaseofLearnSM_matrix(4,1:4), EaseofLearnSM_matrix(12,1:4),...
                EaseofLearnSM_matrix(13,1:4), EaseofLearnSM_matrix(14,1:4)];
            

EaseofLearnMMC_matrix = table2array(Learn(18:31,3:6));

EaseofLearnMMC_orderofquestionC = reshape(EaseofLearnMMC_matrix,[1,56]);

EaseofLearnMMC_subjectorderC = [EaseofLearnMMC_matrix(1,1:4), EaseofLearnMMC_matrix(2,1:4),... 
                EaseofLearnMMC_matrix(3,1:4), EaseofLearnMMC_matrix(4,1:4),...
                EaseofLearnMMC_matrix(5,1:4), EaseofLearnMMC_matrix(6,1:4),...
                EaseofLearnMMC_matrix(7,1:4), EaseofLearnMMC_matrix(8,1:4),...
                EaseofLearnMMC_matrix(9,1:4), EaseofLearnMMC_matrix(10,1:4),...
                EaseofLearnMMC_matrix(4,1:4), EaseofLearnMMC_matrix(12,1:4),...
                EaseofLearnMMC_matrix(13,1:4), EaseofLearnMMC_matrix(14,1:4)];

          
EaseofLearnORT_matrix = table2array(Learn(35:48,3:6));

EaseofLearnORT_orderofquestionC = reshape(EaseofLearnORT_matrix,[1,56]);

EaseofLearnORT_subjectorderC = [EaseofLearnORT_matrix(1,1:4), EaseofLearnORT_matrix(2,1:4),... 
                EaseofLearnORT_matrix(3,1:4), EaseofLearnORT_matrix(4,1:4),...
                EaseofLearnORT_matrix(5,1:4), EaseofLearnORT_matrix(6,1:4),...
                EaseofLearnORT_matrix(7,1:4), EaseofLearnORT_matrix(8,1:4),...
                EaseofLearnORT_matrix(9,1:4), EaseofLearnORT_matrix(10,1:4),...
                EaseofLearnORT_matrix(4,1:4), EaseofLearnORT_matrix(12,1:4),...
                EaseofLearnORT_matrix(13,1:4), EaseofLearnORT_matrix(14,1:4)];
            
            
EaseofLearnSM_subjectorderA = table2array(Learn(52,3:6));
EaseofLearnMMC_subjectorderA = table2array(Learn(54,3:6));
EaseofLearnORT_subjectorderA = table2array(Learn(56,3:6));

EaseofLearnSM_subjectorderB = table2array(Learn(58,3:6));
EaseofLearnMMC_subjectorderB = table2array(Learn(60,3:6));
EaseofLearnORT_subjectorderB = table2array(Learn(62,3:6));


%% Satisfaction

Satisfaction = readtable("Satisfaction.xlsx");

SatisfactionSM_matrix = table2array(Satisfaction(1:14,3:7));

SatisfactionSM_orderofquestionC = reshape(SatisfactionSM_matrix,[1,70]);

SatisfactionSM_subjectorderC = [SatisfactionSM_matrix(1,1:5), SatisfactionSM_matrix(2,1:5),... 
                SatisfactionSM_matrix(3,1:5), SatisfactionSM_matrix(4,1:5),...
                SatisfactionSM_matrix(5,1:5), SatisfactionSM_matrix(6,1:5),...
                SatisfactionSM_matrix(7,1:5), SatisfactionSM_matrix(8,1:5),...
                SatisfactionSM_matrix(9,1:5), SatisfactionSM_matrix(10,1:5),...
                SatisfactionSM_matrix(4,1:5), SatisfactionSM_matrix(12,1:5),...
                SatisfactionSM_matrix(13,1:5), SatisfactionSM_matrix(14,1:5)];
            

SatisfactionMMC_matrix = table2array(Satisfaction(18:31,3:7));

SatisfactionMMC_orderofquestionC = reshape(SatisfactionMMC_matrix,[1,70]);

SatisfactionMMC_subjectorderC = [SatisfactionMMC_matrix(1,1:5), SatisfactionMMC_matrix(2,1:5),... 
                SatisfactionMMC_matrix(3,1:5), SatisfactionMMC_matrix(4,1:5),...
                SatisfactionMMC_matrix(5,1:5), SatisfactionMMC_matrix(6,1:5),...
                SatisfactionMMC_matrix(7,1:5), SatisfactionMMC_matrix(8,1:5),...
                SatisfactionMMC_matrix(9,1:5), SatisfactionMMC_matrix(10,1:5),...
                SatisfactionMMC_matrix(4,1:5), SatisfactionMMC_matrix(12,1:5),...
                SatisfactionMMC_matrix(13,1:5), SatisfactionMMC_matrix(14,1:5)];

            
SatisfactionORT_matrix = table2array(Satisfaction(35:48,3:7));

SatisfactionORT_orderofquestionC = reshape(SatisfactionORT_matrix,[1,70]);

SatisfactionORT_subjectorderC = [SatisfactionORT_matrix(1,1:5), SatisfactionORT_matrix(2,1:5),... 
                SatisfactionORT_matrix(3,1:5), SatisfactionORT_matrix(4,1:5),...
                SatisfactionORT_matrix(5,1:5), SatisfactionORT_matrix(6,1:5),...
                SatisfactionORT_matrix(7,1:5), SatisfactionORT_matrix(8,1:5),...
                SatisfactionORT_matrix(9,1:5), SatisfactionORT_matrix(10,1:5),...
                SatisfactionORT_matrix(4,1:5), SatisfactionORT_matrix(12,1:5),...
                SatisfactionORT_matrix(13,1:5), SatisfactionORT_matrix(14,1:5)];
            
            
SatisfactionSM_subjectorderA = table2array(Satisfaction(52,3:7));
SatisfactionMMC_subjectorderA = table2array(Satisfaction(54,3:7));
SatisfactionORT_subjectorderA = table2array(Satisfaction(56,3:7));

SatisfactionSM_subjectorderB = table2array(Satisfaction(58,3:7));
SatisfactionMMC_subjectorderB = table2array(Satisfaction(60,3:7));
SatisfactionORT_subjectorderB = table2array(Satisfaction(62,3:7));


%% 
clearvars -except EaseofUseSM_subjectorderC EaseofUseMMC_subjectorderC EaseofUseORT_subjectorderC...
                    EaseofUseSM_subjectorderA EaseofUseMMC_subjectorderA EaseofUseORT_subjectorderA...
                    EaseofUseSM_subjectorderB EaseofUseMMC_subjectorderB EaseofUseORT_subjectorderB...
                    EaseofLearnSM_subjectorderC EaseofLearnMMC_subjectorderC EaseofLearnORT_subjectorderC...
                    EaseofLearnSM_subjectorderA EaseofLearnMMC_subjectorderA EaseofLearnORT_subjectorderA...
                    EaseofLearnSM_subjectorderB EaseofLearnMMC_subjectorderB EaseofLearnORT_subjectorderB...
                    SGrouatisfactionSM_subjectorderC SatisfactionMMC_subjectorderC SatisfactionORT_subjectorderC...
                    SatisfactionSM_subjectorderA SatisfactionMMC_subjectorderA SatisfactionORT_subjectorderA...
                    SatisfactionSM_subjectorderB SatisfactionMMC_subjectorderB SatisfactionORT_subjectorderB

                
                
EaseofUseSM_subjectorderC = EaseofUseSM_subjectorderC';
EaseofUseMMC_subjectorderC = EaseofUseMMC_subjectorderC';
EaseofUseORT_subjectorderC = EaseofUseORT_subjectorderC';
EaseofUseSM_subjectorderA = EaseofUseSM_subjectorderA';
EaseofUseMMC_subjectorderA = EaseofUseMMC_subjectorderA';
EaseofUseORT_subjectorderA = EaseofUseORT_subjectorderA';
EaseofUseSM_subjectorderB = EaseofUseSM_subjectorderB';
EaseofUseMMC_subjectorderB = EaseofUseMMC_subjectorderB';
EaseofUseORT_subjectorderB = EaseofUseORT_subjectorderB';
EaseofLearnSM_subjectorderC = EaseofLearnSM_subjectorderC';
EaseofLearnMMC_subjectorderC = EaseofLearnMMC_subjectorderC';
EaseofLearnORT_subjectorderC = EaseofLearnORT_subjectorderC';
EaseofLearnSM_subjectorderA = EaseofLearnSM_subjectorderA';
EaseofLearnMMC_subjectorderA = EaseofLearnMMC_subjectorderA';
EaseofLearnORT_subjectorderA = EaseofLearnORT_subjectorderA';
EaseofLearnSM_subjectorderB = EaseofLearnSM_subjectorderB';
EaseofLearnMMC_subjectorderB = EaseofLearnMMC_subjectorderB';
EaseofLearnORT_subjectorderB = EaseofLearnORT_subjectorderB';
SatisfactionSM_subjectorderC = SatisfactionSM_subjectorderC';
SatisfactionMMC_subjectorderC = SatisfactionMMC_subjectorderC';
SatisfactionORT_subjectorderC = SatisfactionORT_subjectorderC';
SatisfactionSM_subjectorderA = SatisfactionSM_subjectorderA';
SatisfactionMMC_subjectorderA = SatisfactionMMC_subjectorderA';
SatisfactionORT_subjectorderA = SatisfactionORT_subjectorderA';
SatisfactionSM_subjectorderB = SatisfactionSM_subjectorderB';
SatisfactionMMC_subjectorderB = SatisfactionMMC_subjectorderB';
SatisfactionORT_subjectorderB = SatisfactionORT_subjectorderB';
